name: Deploy Laravel

on:
  push:
    branches: [ main ] #Running the runner when main is push
    
jobs:
  deploy:
    runs-on: self-hosted #indicates that the action will run on a self hosted
    
    steps:
      - uses: actions/checkout@v4 #to clone a repository into the runner's workspace

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Laravel setup #Running the laravel necessery setup
        run: |
          composer update
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
